export const products = [
  {
    id: 1,
    brand: "Roadster",
    name: "Cotton Checked Casual Shirt",
    image: "1.jpg",
    price: 69999,
    discount: 10,
    discountPrice: 69999 - (10 / 100) * 69999,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 5,
    ratings: 5,
  },
  {
    id: 2,
    brand: "LouisPhilippe",
    name: "Cotton Checked Casual Shirt",
    image: "2.jpg",
    price: 8999,
    discount: 60,
    discountPrice: 8999 - (60 / 100) * 8999,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 0,
    ratings: 5,
  },
  {
    id: 3,
    brand: "Roadster",
    name: "Cotton Checked Casual Shirt",
    image: "3.jpg",
    price: 19999,
    discount: 1,
    discountPrice: 19999 - (1 / 100) * 19999,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 1,
  },
  {
    id: 4,
    brand: "LouisPhilippe",
    name: "borad Shirt",
    image: "4.jpg",
    price: 24999,
    discount: 5,
    discountPrice: 24999 - (5 / 100) * 24999,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 0,
  },
  {
    id: 5,
    brand: "Roadster",
    name: "nylon Shirt",
    image: "5.jpg",
    price: 39999,
    discount: 10,
    discountPrice: 39900 - (10 / 100) * 39999,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 5,
  },
  {
    id: 6,
    brand: "AllenSolly",
    name: "silky Shirt",
    image: "6.jpg",
    price: 15599,
    discount: 60,
    discountPrice: 15599 - (60 / 100) * 15599,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 2,
  },
  {
    id: 7,
    brand: "AllenSolly",
    name: "redcarpet ",
    image: "7.jpg",
    price: 1299,
    discount: 10,
    discountPrice: 1299 - (10 / 100) * 1299,
    quantity: 1,
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 4,
  },
  {
    id: 8,
    brand: "Roadster",
    name: "wollen Checked Casual Shirt",
    image: "8.jpg",
    price: 20999,
    discount: 5,
    discountPrice: 20999 - (5 / 100) * 20999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 3,
  },

  {
    id: 9,
    brand: "Roadster",
    name: "wollen Checked Casual Shirt",
    image: "9.jpg",
    price: 169999,
    discount: 10,
    discountPrice: 169999 - (10 / 100) * 169999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "men",
    instock: 40,
    ratings: 3,
  },
  {
    id: 10,
    brand: "AllenSolly",
    name: "wollen Checked Casual Shirt",
    image: "10.jpg",
    price: 16999,
    discount: 60,
    discountPrice: 16999 - (60 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
  {
    id: 11,
    brand: "AllenSolly",
    name: "wollen Checked Casual Shirt",
    image: "11.jpg",
    price: 16999,
    discount: 60,
    discountPrice: 16999 - (60 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
  {
    id: 12,
    brand: "HighLander",
    name: "wollen Checked Casual Shirt",
    image: "12.jpg",
    price: 24999,
    discount: 60,
    discountPrice: 24999 - (60 / 100) * 24999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
  {
    id: 13,
    brand: "Roadster",
    name: "wollen Checked Casual Shirt",
    image: "13.jpg",
    price: 1699,
    discount: 20,
    discountPrice: 1699 - (20 / 100) * 1699,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
  {
    id: 14,
    brand: "HighLander",
    name: "wollen Checked Casual Shirt",
    image: "14.jpg",
    price: 5999,
    discount: 10,
    discountPrice: 5999 - (10 / 100) * 5999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
  {
    id: 15,
    brand: "LouisPhilippe",
    name: "wollen Checked Casual Shirt",
    image: "15.jpg",
    price: 16999,
    discount: 5,
    discountPrice: 16999 - (5 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "boys",
    instock: 40,
    ratings: 3,
  },

  {
    id: 16,
    brand: "AllenSolly",
    name: "wollen Checked Casual Shirt",
    image: "16.jpg",
    price: 16999,
    discount: 6,
    discountPrice: 16999 - (6 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "boys",
    instock: 40,
    ratings: 3,
  },
  {
    id: 17,
    brand: "Roadster",
    name: "wollen Checked Casual Shirt",
    image: "17.jpg",
    price: 16999,
    discount: 4,
    discountPrice: 16999 - (4 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "boys",
    instock: 40,
    ratings: 3,
  },
  {
    id: 18,
    brand: "HighLander",
    name: "wollen Checked Casual Shirt",
    image: "18.jpg",
    price: 7169,
    discount: 60,
    discountPrice: 7169 - (60 / 100) * 7169,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "girls",
    instock: 40,
    ratings: 3,
  },
  {
    id: 19,
    brand: "AllenSolly",
    name: "wollen Checked Casual Shirt",
    image: "19.jpg",
    price: 7169,
    discount: 30,
    discountPrice: 7169 - (60 / 100) * 7169,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "girls",
    instock: 40,
    ratings: 3,
  },
  {
    id: 20,
    brand: "AllenSolly",
    name: "wollen Checked Casual Shirt",
    image: "20.jpg",
    price: 3599,
    discount: 20,
    discountPrice: 3599 - (20 / 100) * 3599,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "girls",
    instock: 40,
    ratings: 3,
  },
  {
    id: 21,
    brand: "HighLander",
    name: "wollen Checked Casual Shirt",
    image: "21.jpg",
    price: 7169,
    discount: 40,
    discountPrice: 7169 - (40 / 100) * 7169,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "girls",
    instock: 40,
    ratings: 3,
  },
  {
    id: 22,
    brand: "LouisPhilippe",
    name: "wollen Checked Casual Shirt",
    image: "22.jpg",
    price: 79999,
    discount: 20,
    discountPrice: 79999 - (20 / 100) * 79999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "girls",
    instock: 40,
    ratings: 3,
  },
  {
    id: 23,
    brand: "LouisPhilippe",
    name: "wollen Checked Casual Shirt",
    image: "23.jpg",
    price: 26999,
    discount: 10,
    discountPrice: 26999 - (10 / 100) * 26999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "girls",
    instock: 40,
    ratings: 3,
  },
  {
    id: 24,
    brand: "LouisPhilippe",
    name: "wollen Checked Casual Shirt",
    image: "24.jpg",
    price: 12999,
    discount: 2,
    discountPrice: 12999 - (2 / 100) * 126999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "boys",
    instock: 40,
    ratings: 3,
  },
  {
    id: 25,
    brand: "HighLander",
    name: "wollen Checked Casual Shirt",
    image: "25.jpg",
    price: 16999,
    discount: 6,
    discountPrice: 16999 - (6 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "boys",
    instock: 40,
    ratings: 3,
  },
  {
    id: 26,
    brand: "LouisPhilippe",
    name: "wollen Checked Casual Shirt",
    image: "26.jpg",
    price: 16999,
    discount: 5,
    discountPrice: 16999 - (5 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
  {
    id: 27,
    brand: "HighLander",
    name: "wollen Checked Casual Shirt",
    image: "27.jpg",
    price: 16999,
    discount: 70,
    discountPrice: 16999 - (70 / 100) * 16999,
    quantity: 1,

    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
    for: "wom",
    instock: 40,
    ratings: 3,
  },
];
